#!/usr/bin/env bash
# This script displays "Best School" 10 time using a while loop

var=1

while [ $var -lt 10 ]; do
	if [ $var -eq 8 ]; then
		echo -e "Best School\nHi"
	else
		echo "Best School"
	fi
	((var++))
done
