#!/usr/bin/env bash
# This script displays "Best School" 10 time using a while loop

var=1

while [ $var -le 10 ]; do
	if [ $var -ne 9 ]; then
		echo "Best School"
	else
		echo "Hi"
	fi
	((var++))
done
