#!/usr/bin/env bash
# This script displays "bad luck" on the 4th iteration and 
# and "good luck" on the 8th iteration else "Best School" 

var=1

while [ $var -le 10 ]; do
	if [ $var -eq 4 ]; then
		echo  "bad luck"
	elif [ $var -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	((var++))
done
