#!/usr/bin/env bash
# Display "Hour: `hour_number`", and then each minute from 0 to 59
# on a new line

hour=0

while [ $hour -le 12 ]; do
	echo "Hour: $hour"

	minute=1
	while [ $minute -lt 60 ]; do
		echo "$minute"
		((minute++))
	done
	((hour++))
done
