#!/usr/bin/env bash
# Check the state of a file

# Check if school file exist or not
if [ -e "school" ]; then
	echo "school file exists"
	
	# Check if school file is empty or not
	if [ -s "school" ]; then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi

	# Check if school file is a regular file
	if [ -f "school" ]; then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi

